### ISSUE TITLE
[BUG] Button is almost off-screen.

### ISSUE THREAD

**Issue by Zorklis** [mooziii/epic-reload-mod#3]
![image](https://user-images.githubusercontent.com/85455465/200327753-fb70c7eb-68dd-4a59-bf3b-622ef300cf6f.png)

**Comment by mooziii** [comment]
## Known bugs

When using with ModMenu, the `Mods Button` setting from ModMenu should be set to `Adjacent`
![ModMenu](https://i.imgur.com/YZO8w42.png)
